config/routes.rb
MattressShop::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'home#index'
  get "home/index"

  match '/articles' => 'pages#articles'
  #match '/articles', :to => 'pages#articles'


  devise_for :users

  resources :mattresses, :only => [:index, :show]
  resources :product_series, :only => [] do
    resources :mattresses, :only => [:index, :show]
  end
  resources :manufacturers, :only => [] do
    resources :mattresses, :only => [:index, :show]
  end

  resources :pages, only: [:show]

  namespace :admin do
    root :to => 'mattresses#index'
    resources :product_series
    resources :manufacturers
    resources :mattresses
    resources :page_parts
    resources :bulk_price_changes, only: [:new, :create]
    resources :seos
  end

end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  include SeoLogic
  attr_accessible :logo, :name, :logo_cache, :remove_logo
  mount_uploader :logo, ManufacturerLogoUploader

  has_many :product_serieses, :class_name => 'ProductSeries'
  has_many :mattresses, :through => :product_serieses

  scope :for_header, order('id ASC').limit(4)
end

app/controllers/admin/manufacturers_controller.rb
class Admin::ManufacturersController < Admin::ApplicationController
  # GET /manufacturers
  # GET /manufacturers.json
  def index
    @manufacturers = Manufacturer.all
    @seo = Manufacturer.seo

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @manufacturers }
    end
  end

  # GET /manufacturers/1
  # GET /manufacturers/1.json
  def show
    @manufacturer = Manufacturer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manufacturer }
    end
  end

  # GET /manufacturers/new
  # GET /manufacturers/new.json
  def new
    @manufacturer = Manufacturer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @manufacturer }
    end
  end

  # GET /manufacturers/1/edit
  def edit
    @manufacturer = Manufacturer.find(params[:id])
  end

  # POST /manufacturers
  # POST /manufacturers.json
  def create
    @manufacturer = Manufacturer.new(params[:manufacturer])

    respond_to do |format|
      if @manufacturer.save
        format.html { redirect_to [:admin, @manufacturer], notice: 'Manufacturer was successfully created.' }
        format.json { render json: @manufacturer, status: :created, location: [:admin, @manufacturer] }
      else
        format.html { render action: "new" }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /manufacturers/1
  # PUT /manufacturers/1.json
  def update
    @manufacturer = Manufacturer.find(params[:id])

    respond_to do |format|
      if @manufacturer.update_attributes(params[:manufacturer])
        format.html { redirect_to [:admin, @manufacturer], notice: 'Manufacturer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufacturers/1
  # DELETE /manufacturers/1.json
  def destroy
    @manufacturer = Manufacturer.find(params[:id])
    @manufacturer.destroy

    respond_to do |format|
      format.html { redirect_to admin_manufacturers_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/manufacturers/_form.html.slim
= simple_form_for [:admin, @manufacturer], :html => { :class => "form-horizontal" } do |f|
  = f.input :name
  = image_fiels_for(f, :logo)
  - f.object.build_seo unless f.object.seo
  = f.simple_fields_for :seo do |seo_f|
    = render 'admin/seos/form', :f => seo_f
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_manufacturers_path, :class => 'btn'

app/views/admin/manufacturers/edit.html.slim
- model_class = Manufacturer
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/manufacturers/index.html.slim
- model_class = Manufacturer
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @manufacturers.each do |manufacturer|
      tr
        td= link_to manufacturer.id, admin_manufacturer_path(manufacturer)
        td= manufacturer.name
        td=l manufacturer.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_manufacturer_path(manufacturer), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_manufacturer_path(manufacturer), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_admin_manufacturer_path, :class => 'btn btn-primary'

= render 'admin/seos/full_form'

app/views/admin/manufacturers/new.html.slim
- model_class = Manufacturer
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/manufacturers/show.html.slim
- model_class = Manufacturer
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @manufacturer.name
p
  strong= model_class.human_attribute_name(:logo) + ':'
  br
  = image_tag(@manufacturer.logo.url(:processed)) if @manufacturer.logo?

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_manufacturers_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_manufacturer_path(@manufacturer), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_manufacturer_path(@manufacturer), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'