config/routes.rb
MattressShop::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'home#index'
  get "home/index"

  match '/articles' => 'pages#articles'
  #match '/articles', :to => 'pages#articles'


  devise_for :users

  resources :mattresses, :only => [:index, :show]
  resources :product_series, :only => [] do
    resources :mattresses, :only => [:index, :show]
  end
  resources :manufacturers, :only => [] do
    resources :mattresses, :only => [:index, :show]
  end

  resources :pages, only: [:show]

  namespace :admin do
    root :to => 'mattresses#index'
    resources :product_series
    resources :manufacturers
    resources :mattresses
    resources :page_parts
    resources :bulk_price_changes, only: [:new, :create]
    resources :seos
  end

end

app/models/page_part.rb
class PagePart < ActiveRecord::Base
  include SeoLogic

  attr_accessible :content, :key, :title, :intro
  validate :key,
    :presence => true,
    :uniqueness => true

  before_validation :set_uniq_key, :if => :new_record?

  PART_KEYS = %w[
    phones_header phones_footer copyright banner
  ]
  DEFAULT_PAGES = %w[
    about payment_and_delivery contact_info
  ]
  DEFAULT_KEYS = PART_KEYS + DEFAULT_PAGES

  scope :articles, where("page_parts.key NOT IN (?)", DEFAULT_KEYS)

  scope :deletable, articles

  scope :other_than, ->(exclusion) { where("page_parts.id NOT IN (?)", exclusion) }

  def self.[](key)
    key = key.to_s
    logger.info('Looking for %s, but not found' % key) unless  self.find_by_key(key).try(:content)

    self.find_by_key(key)
  end

  def default?
    DEFAULT_KEYS.include?(self.key)
  end

  def deletable?
    !default?
  end

  def to_s
    self.content || ''
  end

  protected
  def set_uniq_key
    self.key ||= SecureRandom.hex
  end
end

app/controllers/admin/page_parts_controller.rb
class Admin::PagePartsController < Admin::ApplicationController
  # GET /page_parts
  # GET /page_parts.json
  def index
    @page_parts = PagePart.all
    @seo = PagePart.seo

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @page_parts }
    end
  end

  # GET /page_parts/1
  # GET /page_parts/1.json
  def show
    @page_part = PagePart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page_part }
    end
  end

  # GET /page_parts/new
  # GET /page_parts/new.json
  def new
    @page_part = PagePart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page_part }
    end
  end

  # GET /page_parts/1/edit
  def edit
    @page_part = PagePart.find(params[:id])
  end

  # POST /page_parts
  # POST /page_parts.json
  def create
    @page_part = PagePart.new(params[:page_part])

    respond_to do |format|
      if @page_part.save
        format.html { redirect_to [:admin, @page_part], notice: 'Page part was successfully created.' }
        format.json { render json: @page_part, status: :created, location: [:admin, @page_part] }
      else
        format.html { render action: "new" }
        format.json { render json: @page_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /page_parts/1
  # PUT /page_parts/1.json
  def update
    @page_part = PagePart.find(params[:id])

    respond_to do |format|
      if @page_part.update_attributes(params[:page_part])
        format.html { redirect_to [:admin, @page_part], notice: 'Page part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_parts/1
  # DELETE /page_parts/1.json
  def destroy
    @page_part = PagePart.deletable.find(params[:id])
    @page_part.destroy

    respond_to do |format|
      format.html { redirect_to admin_page_parts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/page_parts_helper.rb
module PagePartsHelper
  # Options:
  # :wrap_in - html tag to wrap links
  # :separator - delimiter to insert between elements
  def page_parts_menu_links(options = {})
    %w[contact_info payment_and_delivery].map do |key|
      element = link_to PagePart[key].title, page_path(PagePart[key])
      element = content_tag(options[:wrap_in], element.html_safe) if options[:wrap_in]
      element
    end.join(" #{options[:separator]}\n").html_safe
  end
end

app/views/admin/page_parts/_form.html.slim
= simple_form_for [:admin, @page_part], :html => { :class => "form-horizontal" } do |f|
  /= f.input :key
  = f.input :title
  = f.input :intro, :as => :ckeditor
  = f.input :content, :as => :ckeditor
  - f.object.build_seo unless f.object.seo
  = f.simple_fields_for :seo do |seo_f|
    = render 'admin/seos/form', :f => seo_f
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_page_parts_path, :class => 'btn'

app/views/admin/page_parts/edit.html.slim
- model_class = PagePart
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/page_parts/index.html.slim
- model_class = PagePart
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      /th= model_class.human_attribute_name(:key)
      th= model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @page_parts.each do |page_part|
      tr
        td= link_to page_part.id, admin_page_part_path(page_part)
        /td= page_part.key
        td= page_part.title
        td=l page_part.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_page_part_path(page_part), :class => 'btn btn-mini'
          -if page_part.deletable?
            '
            = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_page_part_path(page_part), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_admin_page_part_path, :class => 'btn btn-primary'

= render 'admin/seos/full_form'

app/views/admin/page_parts/new.html.slim
- model_class = PagePart
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/page_parts/show.html.slim
- model_class = PagePart
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human

/p
  /strong= model_class.human_attribute_name(:key) + ':'
  /br
  /= @page_part.key
p
  strong= model_class.human_attribute_name(:title) + ':'
  br
  = @page_part.title
p
  strong= model_class.human_attribute_name(:intro) + ':'
  br
  == @page_part.intro

p
  strong= model_class.human_attribute_name(:content) + ':'
  br
  == @page_part.content

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_page_parts_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_page_part_path(@page_part), :class => 'btn'
  -if @page_part.deletable?
    '
    = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_page_part_path(@page_part), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'