config/routes.rb
MattressShop::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'home#index'
  get "home/index"

  match '/articles' => 'pages#articles'
  #match '/articles', :to => 'pages#articles'


  devise_for :users

  resources :mattresses, :only => [:index, :show]
  resources :product_series, :only => [] do
    resources :mattresses, :only => [:index, :show]
  end
  resources :manufacturers, :only => [] do
    resources :mattresses, :only => [:index, :show]
  end

  resources :pages, only: [:show]

  namespace :admin do
    root :to => 'mattresses#index'
    resources :product_series
    resources :manufacturers
    resources :mattresses
    resources :page_parts
    resources :bulk_price_changes, only: [:new, :create]
    resources :seos
  end

end

app/controllers/admin/mattresses_controller.rb
class Admin::MattressesController < Admin::ApplicationController
  # GET /mattresses
  # GET /mattresses.json
  def index
    @filter = params[:filter] || {}
    @filter[:manufacturers] = @filter[:manufacturers].presence || Manufacturer.scoped.pluck(:id)
    @filter[:manufacturers].select!(&:present?)
    @filter[:manufacturers].map!(&:to_i)
    @filter[:product_serieses] = @filter[:product_serieses].presence || ProductSeries.scoped.pluck(:id)
    @filter[:product_serieses].select!(&:present?)
    @filter[:product_serieses].map!(&:to_i)


    @mattresses = Mattress.includes(:product_series).where{product_series.id.in my{@filter[:product_serieses]}}
    @seo = Mattress.seo

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mattresses }
    end
  end

  # GET /mattresses/1
  # GET /mattresses/1.json
  def show
    @mattress = Mattress.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mattress }
    end
  end

  # GET /mattresses/new
  # GET /mattresses/new.json
  def new
    @mattress = Mattress.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mattress }
    end
  end

  # GET /mattresses/1/edit
  def edit
    @mattress = Mattress.find(params[:id])
  end

  # POST /mattresses
  # POST /mattresses.json
  def create
    @mattress = Mattress.new(params[:mattress])

    respond_to do |format|
      if @mattress.save
        format.html { redirect_to [:admin, @mattress], notice: 'Mattress was successfully created.' }
        format.json { render json: @mattress, status: :created, location: @mattress }
      else
        format.html { render action: "new" }
        format.json { render json: @mattress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mattresses/1
  # PUT /mattresses/1.json
  def update
    @mattress = Mattress.find(params[:id])

    respond_to do |format|
      if @mattress.update_attributes(params[:mattress])
        format.html { redirect_to [:admin, @mattress], notice: 'Mattress was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mattress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mattresses/1
  # DELETE /mattresses/1.json
  def destroy
    @mattress = Mattress.find(params[:id])
    @mattress.destroy

    respond_to do |format|
      format.html { redirect_to admin_mattresses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/mattresses_controller.rb
# coding: utf-8"

class MattressesController < ApplicationController
  before_filter :find_context, :only => :index

  before_filter :load_menu_data

  def index
    #TODO pagination
    @mattresses = (@current_product_series || @current_manufacturer).mattresses.front_listing.page(params[:page])
    @spalni = (@current_manufacturer.name.casecmp('Спальни') == 0)
  end

  def show
    @mattress = Mattress.includes(:product_series, :manufacturer).find(params[:id])
    @current_product_series = @mattress.product_series
    @current_manufacturer = @mattress.manufacturer
    @spalni = (@current_manufacturer.name.casecmp('Спальни') == 0)
  end

  protected
  def load_menu_data
    @manufacturers = Manufacturer.includes(:product_serieses)
  end
  def find_context
    @current_manufacturer = Manufacturer.find(params[:manufacturer_id]) if params[:manufacturer_id]
    @current_product_series = ProductSeries.find(params[:product_series_id]) if params[:product_series_id]
    #@current_product_series ||= (@current_manufacturer.try(:product_serieses) || ProductSeries).first
    @current_manufacturer = @current_product_series.manufacturer if @current_product_series
    @current_manufacturer ||= Manufacturer.first
  end
end

app/helpers/admin/mattresses_helper.rb
module Admin::MattressesHelper
  def mattress_sizes_collection
    MattressStuff::Size.all.map {|size| [size.width_height, size.id] }
  end
end

app/views/admin/mattresses/_filters.html.slim
= simple_form_for :filter, :url => admin_mattresses_path, :method => :get do |f|
  ul.toggable-container.mattresses-filter
    li
      =label_tag do
        = check_box_tag '', '', false, :class => 'toggle_all_link'
        | All
      = hidden_field_tag 'filter[manufacturers][]'
    - ::Manufacturer.includes(:product_serieses).find_each do |manufacturer|
      li.toggable-container
        = label_tag do
          = check_box_tag 'filter[manufacturers][]',
            manufacturer.id,
            @filter[:manufacturers].include?(manufacturer.id),
            :class => 'toggable manufacturer toggle_all_link',
            :id => "filter_manufacturers_#{manufacturer.id}"
          | #{manufacturer.name}:
        ul.product-series-filter
          li
            /=label_tag do
              /= check_box_tag '', '', false, :class => 'toggle_all_link'
              /| All
            = hidden_field_tag 'filter[product_serieses][]'
          -manufacturer.product_serieses.each do |product_series|
            li
              = label_tag do
                = check_box_tag "filter[product_serieses][]",
                  product_series.id,
                  @filter[:product_serieses].include?(product_series.id),
                  :class => 'toggable',
                  :id => "filter_manufacturers_#{manufacturer.id}_product_serieses_#{product_series.id}"
                = product_series.title
        div.clear

  div.clear
  = f.button :submit, 'Filter!'
end

app/views/admin/mattresses/_form.html.slim
= simple_nested_form_for [:admin, @mattress], :html => { :class => "form-horizontal" } do |f|
  = f.input :title
  = f.input :product_series_id, :as => :select, :collection => ProductSeries.includes(:manufacturer), :label_method => :name_with_manufacturer
  = f.input :width
  = f.input :height
  = f.input :hardness
  = f.input :short_description, :as => :ckeditor
  = f.input :description, :as => :ckeditor
  = f.input :price
  = f.input :best_selled
  - %w[image big_image].each do |image|
    = image_fiels_for(f, image)
  /= f.fields_for :price_for_sizes
  /= f.link_to_add 'Add price', :price_for_sizes
  - f.object.build_seo unless f.object.seo
  = f.simple_fields_for :seo do |seo_f|
    = render 'admin/seos/form', :f => seo_f
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_mattresses_path, :class => 'btn'

app/views/admin/mattresses/_price_for_size_fields.html.slim
= f.link_to_remove 'Remove price'
= f.input :size_id, :as => :select, :collection => mattress_sizes_collection
= f.input :price

app/views/admin/mattresses/edit.html.slim
- model_class = Mattress
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/mattresses/index.html.slim
- model_class = Mattress
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
  = render 'filters'
  = link_to 'Change prices', new_admin_bulk_price_change_path, remote: true, class: 'btn'
= link_to t('.new', :default => t("helpers.links.new")), new_admin_mattress_path, :class => 'btn btn-primary'
table class="table table-striped toggable-container"
  thead
    tr
      th= check_box_tag '', '', false, :class => 'toggle_all_link', :id => 'toggle_all_prices_link'
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:title)
      th price
      th= model_class.human_attribute_name(:description)
      th= model_class.human_attribute_name(:created_at)
      th.actions=t '.actions', :default => t("helpers.actions")
  tbody
    - @mattresses.each do |mattress|
      tr
        td= check_box_tag 'bulk_price_change[ids][]', mattress.id, false, id: "bulk_price_change_ids_#{mattress.id}", class: 'toggable'
        td= link_to mattress.id, admin_mattress_path(mattress)
        td= mattress.title
        td= mattress.price
        td== mattress.short_description
        td=l mattress.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_mattress_path(mattress), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_mattress_path(mattress), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'


= render 'admin/seos/full_form'

app/views/admin/mattresses/new.html.slim
- model_class = Mattress
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/mattresses/show.html.slim
- model_class = Mattress
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:title) + ':'
  br
  = @mattress.title
p
  strong= model_class.human_attribute_name(:product_series) + ':'
  br
  = @mattress.product_series.try(:name_with_manufacturer)
p
  strong= model_class.human_attribute_name(:width) + ':'
  br
  = @mattress.width
p
  strong= model_class.human_attribute_name(:height) + ':'
  br
  = @mattress.height
p
  strong= model_class.human_attribute_name(:hardness) + ':'
  br
  = @mattress.hardness
p
  strong= model_class.human_attribute_name(:short_description) + ':'
  br
  == @mattress.short_description
p
  strong= model_class.human_attribute_name(:description) + ':'
  br
  == @mattress.description
p
  strong= model_class.human_attribute_name(:price) + ':'
  br
  = currency @mattress.price
  |  бел. руб
p
  strong= model_class.human_attribute_name(:image) + ':'
  br
  = image_tag @mattress.image.url(:processed) if @mattress.image?
p
  strong= model_class.human_attribute_name(:big_image) + ':'
  br
  = image_tag @mattress.big_image.url(:processed) if @mattress.image?





.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_mattresses_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_mattress_path(@mattress), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_mattress_path(@mattress), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'