config/routes.rb
MattressShop::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'home#index'
  get "home/index"

  match '/articles' => 'pages#articles'
  #match '/articles', :to => 'pages#articles'


  devise_for :users

  resources :mattresses, :only => [:index, :show]
  resources :product_series, :only => [] do
    resources :mattresses, :only => [:index, :show]
  end
  resources :manufacturers, :only => [] do
    resources :mattresses, :only => [:index, :show]
  end

  resources :pages, only: [:show]

  namespace :admin do
    root :to => 'mattresses#index'
    resources :product_series
    resources :manufacturers
    resources :mattresses
    resources :page_parts
    resources :bulk_price_changes, only: [:new, :create]
    resources :seos
  end

end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  div*{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    a.close data-dismiss="alert"
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.slim
= link_to "Mattress Shop", root_path, :class => 'brand'
ul.nav
  - if user_signed_in?
    /- if user_signed_in?
    li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
    /- else
      /li
        /= link_to 'Login', new_user_session_path
    /- if user_signed_in?
    li
      = link_to 'Edit account', edit_user_registration_path
    /- else
      /li
        /= link_to 'Sign up', new_user_registration_path
    li
      a |
    li
      = link_to 'Matresses', admin_mattresses_path
    li
      = link_to 'Page parts', admin_page_parts_path
    li
      = link_to 'Manufacturers', admin_manufacturers_path
    li
      = link_to 'Product series', admin_product_series_index_path

app/views/layouts/admin.html.slim
doctype html
erb:
  <!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
  <!--[if lt IE 7 ]> <html class="ie6"> <![endif]-->
  <!--[if IE 7 ]>    <html class="ie7"> <![endif]-->
  <!--[if IE 8 ]>    <html class="ie8"> <![endif]-->
  <!--[if (gt IE 8)|!(IE)]><!--> <html> <!--<![endif]-->
head
    title= content_for?(:title) ? yield(:title) : "Mattress Shop"
    meta content=(content_for?(:description) ? yield(:description) : "Mattress Shop") name="description"
      = stylesheet_link_tag("admin", :media => "all")
      = javascript_include_tag "admin"
      = csrf_meta_tags
      = yield(:head)
body
  header.navbar.navbar-fixed-top
    nav.navbar-inner
      .container
        = render 'layouts/navigation'
  #main role="main"
    .container
      .content
        .row
          .span12
            = render 'layouts/messages'
            = yield
        footer
    /! ! end of .container
  /! ! end of #main
erb:
  </html>

app/views/layouts/application.html.slim
doctype html
erb:
  <!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
  <!--[if lt IE 7 ]> <html class="ie6"> <![endif]-->
  <!--[if IE 7 ]>    <html class="ie7"> <![endif]-->
  <!--[if IE 8 ]>    <html class="ie8"> <![endif]-->
  <!--[if (gt IE 8)|!(IE)]><!--> <html> <!--<![endif]-->
head
    title= @seo.try(:title) || "Матраскин"
    meta content=(@seo.try(:description) || "Матраскин") name="description"
    meta content=(@seo.try(:keywords) || "Матраскин") name="keywords"
    = stylesheet_link_tag("application", :media => "all")
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
    erb:
      <meta name="google-site-verification" content="B3AoNPd58MsIzUXkv2dfcBrNmcsCFK80TFwZ7GBGSJA" />
      <meta name='yandex-verification' content='734b7c75016e8c5d' />
      <meta name='wmail-verification' content='7b0f42b84e95c1b5' />
      <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-8103149-11']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
      </script>
body
  erb:
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter18640510 = new Ya.Metrika({id:18640510,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/18640510" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
    <div class="app">
        <header>
          <div class="logo">
            <%= link_to image_tag('/img/logo.png'), root_path %>
          </div>
            <div class="title">
              <p> </p>
              <p class="deliv">Бесплатная доставка  <br/>
                               по городу</p>
            </div>
            <%== PagePart[:phones_header] %>
            <div class="clear"></div>
            <nav>
                <%= link_to 'Кровати', mattresses_path %> |
                <%= link_to 'Полезные статьи', articles_path %> |
                <%= page_parts_menu_links(:separator => '|') %>
            </nav>
        </header>
        <div class="container">
            <div class="spalni_link">
              <%= link_to 'Спальни производства Китай', manufacturer_mattresses_path(Manufacturer.find_by_name('Спальни')) if Manufacturer.find_by_name('Спальни').present? %>
              </div>
            <div class="firms">
                <div class="bar"><p>Матрасы от Производителей</p></div>
                <section>
                  <% Manufacturer.for_header.reverse.each do |manufacturer| %>
                    <%= link_to manufacturer.logo? ? image_tag(manufacturer.logo.url(:processed)) : manufacturer.name, manufacturer_mattresses_path(manufacturer) %>
                  <% end %>
                  <div class="clear"></div>
                </section>
            </div>
            <%= yield %>
        </div>
        <footer>
          <%== PagePart[:copyright] %>
          <ul>
            <li><a href="#">Каталог</a></li>
            <%= page_parts_menu_links(:wrap_in => :li) %>
          </ul>
          <%== PagePart[:phones_footer] %>
          <div class="clear"></div>
        </footer>
    </div>
    <!--[if lte IE 9]>
    <script src="js/libs/PIE.js"></script>
    <![endif]-->


    <div class="phones"></div>

erb:
  </html>